import { CHARACTERS, CONFIG, ELEMENT_NAMES, SKILLS } from '../game/config';
import { skillDamage } from '../game/progression';
import type { CharacterId, GameState, Player, UpgradeChoice } from '../game/types';
import type { Settings } from '../storage';
import { COLORS, ROLE_TEXT, attributeRows, escapeHTML, geometry, icon, lifeRow, timeLabel } from './shared';

function dialog(content: string, className = '', label = '游戏面板'): string { return `<div class="overlay-backdrop"><section class="dialog ${className}" role="dialog" aria-modal="true" aria-label="${label}" tabindex="-1">${content}</section></div>`; }
function attributeStrip(player: Player, tag: 'div' | 'span', className: string): string {
  return `<div class="${className}" style="--role-color:${COLORS[player.characterId]}">${[lifeRow(player), ...attributeRows(player)].map(row => `<${tag}><small>${row.label}</small><b>${row.value}</b></${tag}>`).join('')}</div>`;
}
export function pauseHTML(state: GameState): string {
  return dialog(`<div class="dialog-emblem">${icon('pause')}</div><span class="eyebrow">TAKE A BREATH</span><h2>战场已暂停</h2><p>时钟与战斗已冻结。准备好了，再出发。</p>${attributeStrip(state.player, 'div', 'attribute-grid')}<div class="dialog-actions"><button class="primary-button" data-action="resume">${icon('play')} 继续战斗</button><button class="secondary-button" data-action="settings">${icon('settings')} 设置</button><button class="quiet-button" data-action="leave">${icon('home')} 返回首页</button></div>`, 'compact-dialog', '暂停游戏');
}
export function confirmLeaveHTML(): string {
  return dialog(`<div class="dialog-emblem">${icon('home')}</div><h2>结束本次挑战？</h2><p>进行中的对局不会保存，也不计入完成成绩。</p><div class="dialog-actions"><button class="primary-button" data-action="menu">返回首页</button><button class="secondary-button" data-action="pause">留在战场</button></div>`, 'compact-dialog', '确认返回首页');
}
export function helpHTML(inGame: boolean): string {
  return dialog(`<div class="dialog-heading"><span class="eyebrow">HOW TO SURVIVE</span><button class="icon-button" data-action="close" aria-label="关闭操作说明">${icon('close')}</button></div><h2>移动就是你的第一道防线</h2><p>攻击会自动释放。避开危险轮廓，收集浅蓝菱形经验，在每次进化中强化你的构筑。</p><div class="help-grid"><div>${icon('keyboard')}<h3>电脑操作</h3><p><kbd>W A S D</kbd> / 方向键 · 移动<br><kbd>空格</kbd> · 普通技能<br><kbd>Q</kbd> · 大招<br><kbd>Esc</kbd> · 暂停 / 继续</p></div><div>${icon('target')}<h3>手机操作</h3><p>左下摇杆 · 移动<br>右下按钮 · 释放技能<br>可同时移动和施法<br>旋转屏幕后继续同一局</p></div></div><div class="help-note"><b>活下来，然后击破核心。</b><span>每关 5:00：1:30 与 3:30 阶段精英 · 4:00 首领出现 · 5:00 本关结束。击破首领可选大礼包并进入下一关；地图事件为可选奖励；暂停和进化不计时。</span></div><button class="primary-button" data-action="${inGame ? 'close' : 'start-help'}">${inGame ? '知道了' : '准备出战'} ${icon('arrow')}</button>`, '', '操作说明');
}
export function settingsHTML(settings: Settings): string {
  return dialog(`<div class="dialog-heading"><span class="eyebrow">MAKE IT YOURS</span><button class="icon-button" data-action="close" aria-label="关闭设置">${icon('close')}</button></div><h2>游戏设置</h2><p>调整立即生效，并自动保存在此浏览器。</p><div class="settings-list"><label class="setting-row"><span><b>普通技能自动释放</b><small>有合法目标且冷却就绪时释放，大招始终手动。</small></span><input type="checkbox" data-setting="autoSkill" ${settings.autoSkill ? 'checked' : ''}></label><label class="setting-row volume-row"><span><b>音乐音量</b><output id="music-output">${Math.round(settings.music * 100)}%</output></span><input aria-label="音乐音量" type="range" min="0" max="100" value="${Math.round(settings.music * 100)}" data-setting="music"></label><label class="setting-row volume-row"><span><b>音效音量</b><output id="sound-output">${Math.round(settings.sound * 100)}%</output></span><input aria-label="音效音量" type="range" min="0" max="100" value="${Math.round(settings.sound * 100)}" data-setting="sound"></label><label class="setting-row"><span><b>画质</b><small>低画质减少光晕和尾迹，危险提示保持完整。</small></span><select aria-label="画质" data-setting="quality"><option value="default" ${settings.quality === 'default' ? 'selected' : ''}>默认</option><option value="low" ${settings.quality === 'low' ? 'selected' : ''}>低画质</option></select></label><label class="setting-row"><span><b>减少动态效果</b><small>停止装饰旋转，关闭震屏与呼吸动画。</small></span><input type="checkbox" data-setting="reducedMotion" ${settings.reducedMotion ? 'checked' : ''}></label><label class="setting-row"><span><b>受击震屏</b><small>轻微反馈，不改变操作响应。</small></span><input type="checkbox" data-setting="shake" ${settings.shake ? 'checked' : ''}></label></div><button class="primary-button" data-action="close">完成 ${icon('check')}</button>`, 'settings-dialog', '游戏设置');
}
function changeDetail(choice: UpgradeChoice, state: GameState): string {
  if (choice.kind !== 'level' || !choice.skillId) return '';
  const config = SKILLS[choice.skillId], level = choice.currentLevel ?? 1;
  const before = skillDamage(state, choice.skillId), after = config.damage * (1 + CONFIG.baseDamageGrowth * level) * (1 + state.player.damageBonus);
  return `<strong class="change-detail">伤害 ${before.toFixed(1)} <span>→</span> ${after.toFixed(1)}</strong>`;
}
export function upgradeHTML(state: GameState, eventReward: boolean): string {
  const names = { new: '新技能', level: '技能升级', element: '元素注入', behavior: '行为强化', fusion: '元素融合', stat: '属性强化' };
  return dialog(`<div class="upgrade-heading"><span class="eyebrow">${eventReward ? 'EVENT REWARD' : 'EVOLVE YOUR BUILD'}</span><h2>${eventReward ? '试炼完成，选择奖励' : '选择下一次进化'}</h2><p>${eventReward ? '免费强化，不消耗经验。' : `等级 ${state.level} · 让你的几何之力继续生长。`}${state.pendingUpgrades > 1 ? ` 还有 ${state.pendingUpgrades - 1} 次选择。` : ''}</p></div>${attributeStrip(state.player, 'span', 'stat-strip center')}<div class="upgrade-grid">${state.choices.map((choice, index) => `<button class="upgrade-card" data-choice="${choice.id}"><span class="upgrade-kind">${names[choice.kind]}<small>0${index + 1}</small></span>${geometry(choice.skillId ?? choice.element ?? choice.id)}<h3>${escapeHTML(choice.name)}</h3>${choice.currentLevel ? `<span class="upgrade-level">LV. ${choice.currentLevel} → ${choice.currentLevel + 1}</span>` : ''}${changeDetail(choice, state)}<p>${escapeHTML(choice.description)}</p><span class="choose-label">选择此强化 ${icon('arrow')}</span></button>`).join('')}</div><div class="upgrade-footer"><span>战斗已冻结，放心选择。</span><button class="secondary-button" data-action="reroll" ${state.rerolls <= 0 ? 'disabled' : ''}>${icon('reroll')} 重抽 <b>${state.rerolls} / ${CONFIG.maxRerolls}</b></button></div>`, 'upgrade-dialog', '选择强化');
}
export function giftHTML(state: GameState): string {
  return dialog(`<div class="upgrade-heading"><span class="eyebrow">STAGE CLEAR</span><h2>第 ${state.stage} 关通关，选择大礼包</h2><p>清场完毕。选一份强化，进入第 ${state.stage + 1} 关。</p></div>${attributeStrip(state.player, 'span', 'stat-strip center')}<div class="upgrade-grid">${state.gift.map((choice, index) => `<button class="upgrade-card gift-card" data-gift="${choice.id}"><span class="upgrade-kind">通关礼包<small>0${index + 1}</small></span>${geometry(choice.id)}<h3>${escapeHTML(choice.name)}</h3><p>${escapeHTML(choice.description)}</p><span class="choose-label">选择此礼包 ${icon('arrow')}</span></button>`).join('')}</div><div class="upgrade-footer"><span>下一关时间轴将重新开始。</span></div>`, 'upgrade-dialog gift-dialog', '通关大礼包');
}
export function resultHTML(state: GameState, newly: CharacterId[]): string {
  const victory = state.result === 'victory';
  const damage = Object.entries(state.damageBySkill).sort((a, b) => b[1] - a[1]);
  const total = damage.reduce((sum, [, value]) => sum + value, 0);
  const label = (id: string): string => id === 'active' ? ROLE_TEXT[state.player.characterId].active : id === 'ultimate' ? ROLE_TEXT[state.player.characterId].ultimate : SKILLS[id as keyof typeof SKILLS]?.name ?? id;
  return dialog(`<div class="result-heading ${victory ? 'victory' : ''}"><div class="result-symbol">${geometry(victory ? state.player.characterId : 'mine')}</div><span class="eyebrow">${victory ? 'CORE DEFEATED' : 'RUN COMPLETE'}</span><h2>${victory ? '核心已击破' : state.result === 'timeout' ? '未能击破核心' : '本次挑战结束'}</h2><p>${victory ? '你突破了包围。下一种构筑，等待你来探索。' : state.result === 'timeout' ? '本关时间耗尽，核心仍在运转。' : '每一次进化，都是下一次突破的起点。'}</p></div><div class="result-stats"><div><small>到达关卡</small><b>第 ${state.stage} 关</b></div><div><small>本关用时</small><b>${timeLabel(state.time)}</b></div><div><small>总击杀</small><b>${state.kills}</b></div><div><small>最终等级</small><b>${state.level}</b></div></div>${newly.length ? `<div class="unlock-notice">${icon('check')}<div><b>新形态已解锁</b><span>${newly.map(id => CHARACTERS[id].name).join('、')}</span></div></div>` : ''}<div class="result-build"><h3>本局构筑 <span>${CHARACTERS[state.player.characterId].name}</span></h3><div>${state.player.skills.map(skill => `<span>${geometry(skill.id)}<b>${SKILLS[skill.id].name}</b><small>LV.${skill.level} ${skill.elements.map(element => ELEMENT_NAMES[element]).join('＋')}${skill.enhanced ? ' · 强化' : ''}</small></span>`).join('')}</div></div><div class="damage-list"><h3>技能伤害 <small>合计 ${Math.round(total).toLocaleString()}</small></h3>${damage.length ? damage.map(([id, value]) => `<div><span>${label(id)}</span><div class="damage-meter"><i style="width:${total ? value / total * 100 : 0}%;background:${COLORS[state.player.characterId]}"></i></div><b>${Math.round(value).toLocaleString()}</b></div>`).join('') : '<p>本局尚未造成伤害。</p>'}</div><div class="result-actions"><button class="primary-button" data-action="restart">${icon('reroll')} 再来一局</button><button class="secondary-button" data-action="menu">${icon('home')} 返回首页</button></div>`, 'result-dialog', victory ? '胜利结算' : '挑战结算');
}
export function loadingHTML(error = ''): string {
  return dialog(error ? `<div class="dialog-emblem">${icon('warning')}</div><h2>战场暂时无法启动</h2><p>${escapeHTML(error)}</p><button class="primary-button" data-action="retry">${icon('reroll')} 重新加载战场</button>` : '<div class="loading-shape"></div><h2>正在构建竞技场</h2><p>几何核心初始化中…</p>', 'compact-dialog', error ? '加载失败' : '正在加载');
}
